import PaxosFormal.Network
namespace PaxosFormal
set_option maxRecDepth 100000
set_option maxHeartbeats 0
def singleActions : List Action := [.propose 0 1, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0]
def singleResult := runActions singleActions
theorem single_checked : (!singleResult.outside && !singleResult.invalid && (agreement singleResult) && (validity singleResult) && (decisionAccuracy singleResult) && (decisionConsistency singleResult) && (hasChoice singleResult) && (!(allRecognize singleResult))) = true := by
  native_decide
def laterActions : List Action := [.propose 0 1, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .propose 1 2, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1]
def laterResult := runActions laterActions
theorem later_checked : (!laterResult.outside && !laterResult.invalid && (agreement laterResult) && (validity laterResult) && (decisionAccuracy laterResult) && (decisionConsistency laterResult) && (hasChoice laterResult) && (!(allRecognize laterResult))) = true := by
  native_decide
def integerActions : List Action := [.propose 0 4, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .propose 1 5, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1]
def integerResult := runActions integerActions
theorem integer_checked : (!integerResult.outside && !integerResult.invalid && (agreement integerResult) && (validity integerResult) && (decisionAccuracy integerResult) && (decisionConsistency integerResult) && (hasChoice integerResult) && (!(allRecognize integerResult))) = true := by
  native_decide
def concurrentActions : List Action := [.propose 0 1, .propose 1 2, .deliver 0, .deliver 0, .deliver 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0]
def concurrentResult := runActions concurrentActions
theorem concurrent_checked : (!concurrentResult.outside && !concurrentResult.invalid && (agreement concurrentResult) && (validity concurrentResult) && (decisionAccuracy concurrentResult) && (decisionConsistency concurrentResult) && (hasChoice concurrentResult) && (!(allRecognize concurrentResult))) = true := by
  native_decide
def ticksActions : List Action := [.propose 0 1, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2, .tick 0, .tick 1, .tick 2]
def ticksResult := runActions ticksActions
theorem ticks_checked : (!ticksResult.outside && !ticksResult.invalid && (agreement ticksResult) && (validity ticksResult) && (decisionAccuracy ticksResult) && (decisionConsistency ticksResult) && (hasChoice ticksResult) && (!(allRecognize ticksResult))) = true := by
  native_decide
def key_errorActions : List Action := [.propose 0 5, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .deliver 0, .deliver 0, .deliver 0, .resume 0, .receive 0, .deliver 0, .resume 0, .receive 0, .receive 1, .deliver 0, .resume 1, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .receive 2, .deliver 0, .resume 2, .receive 0, .propose 1 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1, .receive 2, .deliver 0, .resume 2, .receive 1, .propose 1 1, .deliver 0, .deliver 0, .deliver 0, .resume 1, .receive 0, .deliver 0, .resume 0, .receive 1, .deliver 0, .resume 1, .receive 1, .receive 2, .deliver 0, .resume 2]
def key_errorResult := runActions key_errorActions
theorem key_error_checked : (!key_errorResult.outside && !key_errorResult.invalid && (agreement key_errorResult) && (validity key_errorResult) && (decisionAccuracy key_errorResult) && (decisionConsistency key_errorResult) && (hasChoice key_errorResult) && (!(allRecognize key_errorResult)) && (key_errorResult.nodes[1]![statusIndex]! == 1)) = true := by
  native_decide
def interleavedActions : List Action := [.propose 0 1, .propose 1 2, .deliver 1, .deliver 1, .deliver 2, .deliver 1, .deliver 0, .receive 2, .deliver 1, .resume 0, .resume 2, .deliver 0, .resume 1, .receive 1, .deliver 0, .receive 2, .deliver 0, .resume 2, .receive 0, .deliver 0, .resume 0, .receive 0, .resume 1, .receive 1, .deliver 1, .deliver 0, .resume 0, .receive 0, .resume 1, .receive 1, .receive 1, .receive 0, .deliver 2, .deliver 0, .deliver 0, .resume 0, .receive 0, .receive 1, .receive 1, .receive 0, .deliver 0, .deliver 0, .resume 1, .receive 2, .resume 0, .receive 0, .deliver 0, .resume 2, .receive 0, .receive 0]
def interleavedResult := runActions interleavedActions
theorem interleaved_checked : (!interleavedResult.outside && !interleavedResult.invalid && (agreement interleavedResult) && (validity interleavedResult) && (decisionAccuracy interleavedResult) && (decisionConsistency interleavedResult) && (hasChoice interleavedResult) && (!(allRecognize interleavedResult))) = true := by
  native_decide
end PaxosFormal
